### ISSUE TITLE
How many bytes with first request?

### ISSUE THREAD

**Issue by JaspaJami** [komoot/BLEConnect#4]
"The komoot app delivers the first 22 Bytes with the first request."

Documentation speaks about 22 bytes, but in my tests its sending max 20 bytes.

**Comment by JaspaJami** [comment]
"You can do subsequent read request with shifted offsets (22) to retrieve more information if the streetname is long. "

Can you explain this, not clear for me. I dont know what kind of request i have to do to get rest of the street name

**Comment by ToBoehmK** [comment]
@JaspaJami thanks for informing us. You are correct: Android can just send 20 bytes at once (23 bytes minus 3 bytes reserved by Android itself) while iOS seems to be able to send 22 - we will update the docs accordingly. 

Regarding you second question this really depends on the platform you are using for connecting to our peripheral. Are you trying to read via the Android SDK framework or do you use something else?

**Comment by danielgard** [comment]
Docs are updated.
